name: Pull Request

on: pull_request

jobs:
  build-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: rustc --version
      - run: make pre-push
  build-1.92:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.92
      - run: make pre-push